import "./globals.css";
import Sidebar from "@/components/Sidebar";


export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
        <Sidebar />
        <div className="ml-16">
          {children}
        </div>
      </body>
    </html>
  );
}
